"""add Publisher Alias table

Revision ID: 09abcc11966c
Revises: e34179986157
Create Date: 2026-08-16 12:11:37.937487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09abcc11966c'
down_revision: Union[str, Sequence[str], None] = 'e34179986157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('publisher', sa.Column('yomigana', sa.String(), nullable=True))
    op.add_column('work_author', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_author', 'role')
    op.drop_column('publisher', 'yomigana')
    op.drop_table('publisher_alias')
    # ### end Alembic commands ###
