"""add payslip seimei_hoken

Revision ID: 1767ed74943c
Revises: 59ad17ee40ea
Create Date: 2026-09-27 18:41:44.936056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1767ed74943c'
down_revision: Union[str, Sequence[str], None] = '59ad17ee40ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payslip', 'seimei_hoekn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payslip', sa.Column('seimei_hoekn', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
