"""add payslip seimei_hoken

Revision ID: 59ad17ee40ea
Revises: 59e9cd874a12
Create Date: 2026-09-27 18:32:55.907791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ad17ee40ea'
down_revision: Union[str, Sequence[str], None] = '59e9cd874a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payslip', sa.Column('seimei_hoekn', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payslip', 'seimei_hoekn')
    # ### end Alembic commands ###
