"""add payslip

Revision ID: 59e9cd874a12
Revises: 4aa1787dcdab
Create Date: 2026-09-27 18:29:27.388849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e9cd874a12'
down_revision: Union[str, Sequence[str], None] = '4aa1787dcdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('honkyu', sa.Integer(), nullable=False),
    sa.Column('noryokukyu', sa.Integer(), nullable=False),
    sa.Column('mibunkyu', sa.Integer(), nullable=False),
    sa.Column('shokuji_teate', sa.Integer(), nullable=False),
    sa.Column('kenkyuin_teate', sa.Integer(), nullable=False),
    sa.Column('tsukin_teate', sa.Integer(), nullable=False),
    sa.Column('jutaku_teate', sa.Integer(), nullable=False),
    sa.Column('nitto_teate', sa.Integer(), nullable=False),
    sa.Column('kekkin_koujo', sa.Integer(), nullable=False),
    sa.Column('jitan_kyushutsu_teate', sa.Integer(), nullable=False),
    sa.Column('shoyo', sa.Integer(), nullable=False),
    sa.Column('shoyo_kakyu', sa.Integer(), nullable=False),
    sa.Column('tokubetsu_kakyu', sa.Integer(), nullable=False),
    sa.Column('tokushu_kinmu_teate', sa.Integer(), nullable=False),
    sa.Column('sonota_shikyu', sa.Integer(), nullable=False),
    sa.Column('kenko_hoken', sa.Integer(), nullable=False),
    sa.Column('kosei_nenkin', sa.Integer(), nullable=False),
    sa.Column('koyo_hoken', sa.Integer(), nullable=False),
    sa.Column('kodomo_shienkin', sa.Integer(), nullable=False),
    sa.Column('shotoku_zei', sa.Integer(), nullable=False),
    sa.Column('jumin_zei', sa.Integer(), nullable=False),
    sa.Column('senyukaihi', sa.Integer(), nullable=False),
    sa.Column('shokuji_dai', sa.Integer(), nullable=False),
    sa.Column('shataku_ryo', sa.Integer(), nullable=False),
    sa.Column('ryohi', sa.Integer(), nullable=False),
    sa.Column('seimei_hoken', sa.Integer(), nullable=False),
    sa.Column('sonota_kojo', sa.Integer(), nullable=False),
    sa.Column('nencho_kabusoku', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslip')
    # ### end Alembic commands ###
