"""add yomigana column to work

Revision ID: 5acf91c76f54
Revises: c320e97987ee
Create Date: 2026-09-11 09:01:08.076033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acf91c76f54'
down_revision: Union[str, Sequence[str], None] = 'c320e97987ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('yomigana', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'yomigana')
    # ### end Alembic commands ###
