"""add note column to author table

Revision ID: 81da088dc300
Revises: 780608cbed93
Create Date: 2026-09-04 09:46:14.850667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81da088dc300'
down_revision: Union[str, Sequence[str], None] = '780608cbed93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('yomigana', sa.String(), nullable=True))
    op.add_column('author', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'note')
    op.drop_column('author', 'yomigana')
    # ### end Alembic commands ###
