"""mod work table

Revision ID: becaab770654
Revises: ec6ab270ac1b
Create Date: 2026-09-05 09:45:38.276260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becaab770654'
down_revision: Union[str, Sequence[str], None] = 'ec6ab270ac1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
