"""add unique constraint to publisher name

Revision ID: e34179986157
Revises: 590e78eca29b
Create Date: 2026-08-14 10:39:16.222885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34179986157'
down_revision: Union[str, Sequence[str], None] = '590e78eca29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'publisher', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publisher', type_='unique')
    # ### end Alembic commands ###
