"""mod work table

Revision ID: ec6ab270ac1b
Revises: 2cb807dbd8e5
Create Date: 2026-09-05 09:43:28.771594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6ab270ac1b'
down_revision: Union[str, Sequence[str], None] = '2cb807dbd8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('work', sa.Column('label_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('work_publisher_id_fkey'), 'work', type_='foreignkey')
    op.create_foreign_key(None, 'work', 'label', ['label_id'], ['id'])
    op.drop_column('work', 'publisher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'work', type_='foreignkey')
    op.create_foreign_key(op.f('work_publisher_id_fkey'), 'work', 'publisher', ['publisher_id'], ['id'])
    op.drop_column('work', 'label_id')
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
